const user = require("express").Router();
const apiRouter = require("./user/api");
const loginRouter = require("./user/login");
const pagesRouter = require("./user/pages");
const registerRouter = require("./user/register");
const logoutRouter = require("./user/logout");
user.use("/api", apiRouter);
user.use("/login", loginRouter);
user.use("/logout", logoutRouter);
user.use("/pages", pagesRouter);
user.use("/register", registerRouter);
module.exports = user;
